name: Quality Assurance
on: [ pull_request, workflow_call ]
jobs:
  lint:
    name: Jetbrains Qodana
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Save credentials
        run: |
          mkdir -p ~/.gradle
          echo gpr.actor=$GITHUB_ACTOR >> ~/.gradle/gradle.properties
          echo gpr.token=$GITHUB_TOKEN >> ~/.gradle/gradle.properties
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2023.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - run: ./gradlew test
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
  codeql:
    permissions:
      actions: read
      contents: read
      security-events: write
      packages: read
    uses: ./.github/workflows/codeql.yml
